DynamoDbEncryption/runtimes/java/build.gradle.kts
Examples/runtimes/java/DynamoDbEncryption/build.gradle.kts
Examples/runtimes/java/Migration/DDBECToAWSDBE/build.gradle.kts
Examples/runtimes/java/Migration/PlaintextToAWSDBE/build.gradle.kts
README.md
TestVectors/runtimes/java/build.gradle.kts

chore(deps): update mpl dependency

---

specification/structured-encryption/encrypt-structure.md

chore: specify origin of the offset parameter

---

DynamoDbEncryption/runtimes/java/src/main/java/software/amazon/cryptography/dbencryptionsdk/dynamodb/enhancedclient/DynamoDbEnhancedClientEncryption.java
DynamoDbEncryption/runtimes/java/src/test/java/software/amazon/cryptography/dbencryptionsdk/dynamodb/enhancedclient/DynamoDbEncryptionEnhancedClientIntegrationTests.java
DynamoDbEncryption/runtimes/java/src/test/java/software/amazon/cryptography/dbencryptionsdk/dynamodb/enhancedclient/DynamoDbEnhancedClientEncryptionTest.java

*Issue #, if available:* `feat(EnhancedClient): Detect Conflicting Configurations`

feat(EnhancedClient): Detect Conflicting Configurations

---

.github/workflows/ci_test_net.yml
specification/structured-encryption/encrypt-structure.md

chore: update workflow file

---

Examples/runtimes/java/DynamoDbEncryption/build.gradle.kts
Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/ConfigUtils.java
Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/ManipulationUtils.java
Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/enhanced/LombokPutGetExample.java
Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/enhanced/SimpleViaLombok.java
Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/enhanced/TableSchemaBuilderPutGetExample.java
Examples/runtimes/java/DynamoDbEncryption/src/test/java/software/amazon/cryptography/examples/enhanced/TestEnhancedPutGetExample.java

*Issue #, if available:* Demonstrate other Enhanced Client CX
*Description of changes:* 
- Add Lombok Plugin to Examples as Dependency
- Add Lombok Example using the Enhanced Client that is a twin of the `EnhancedPutGetExample` 
- Add `TableSchema.builder` example using the Enhanced Client that is a twin of the `EnhancedPutGetExample` 
- Test Lombok and TableSchema support by asserting Signed Fields are handled appropriately
- Test Lombok and TableSchema support by asserting Primary Index members are in Encryption Context to KMS.

feat(example): Use Lombok and Immutable class

---

.github/workflows/ci_examples_java.yml
.github/workflows/ci_test_java.yml
.github/workflows/ci_test_net.yml
.github/workflows/ci_verification.yml

Fixes the fact that the nightly builds are all currently skipped. :)

chore: Replace awslabs with aws in workflows

---

Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/searchableencryption/BasicSearchableEncryptionExample.java

feat: add sleep when query comes up empty

---

.github/dependabot.yml

ci(dependabot):

---

Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/BasicPutGetExample.java

Fix typo in example and add consistent read to simple example.

fix: Add consistent read to basic example

---

CHANGELOG.md
DynamoDbEncryption/runtimes/java/build.gradle.kts
Examples/runtimes/java/DynamoDbEncryption/build.gradle.kts
Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/keyring/KmsRsaKeyringExample.java
Examples/runtimes/java/Migration/DDBECToAWSDBE/build.gradle.kts
Examples/runtimes/java/Migration/PlaintextToAWSDBE/build.gradle.kts
Examples/runtimes/java/Migration/README.md
README.md
TestVectors/runtimes/java/build.gradle.kts

chore: Update for v3.1.0

---

Examples/runtimes/net/src/searchableencryption/BeaconStylesSearchableEncryptionExample.cs

none
Very minor capitalization update

fix: Update minor typo

---

Examples/runtimes/net/src/searchableencryption/complexexample/BeaconConfig.cs

None
Updating minor typos in example file

fix: Update minor typos in BeaconConfig.cs

---

DynamoDbEncryption/runtimes/java/README.md
README.md

docs(README): update README for repo rename update

---

cfn/net/CA-Staging.yml
cfn/net/CB-Release.yml

chore(CFN): add CA & CB templated for dotnet

---

cfn/CB-Staging.yml
cfn/CI.yaml
cfn/code_build_parameter_map.json
cfn/net/CB-Release.yml

chore(CFN): update cfn repo names

---

DynamoDbEncryption/runtimes/net/README.md

feat: Add README for net

---

cfn/CI.yaml

chore: allow codebuild net access to ci resources

---

TestVectors/dafny/DDBEncryption/src/JsonConfig.dfy

chore: minor fixes

---

.github/workflows/ci_test_vector_net.yml
TestVectors/dafny/DDBEncryption/src/Index.dfy
TestVectors/dafny/DDBEncryption/src/TestVectors.dfy

feat: optional tests

---

DynamoDbEncryption/README.md
DynamoDbEncryption/runtimes/net/DynamoDbEncryption.csproj

fix: update readme and csproj file to point to the correct readme

---

Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/CreateKeyStoreKeyExample.java

Repaired example to correct arg index

fix: repair example to correct arg index

---

Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/enhanced/EnhancedPutGetExample.java

feat: add query to enhanced client example

---

Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/searchableencryption/BeaconStylesSearchableEncryptionExample.java
Examples/runtimes/net/src/searchableencryption/BeaconStylesSearchableEncryptionExample.cs

feat: more beacon style examples

---

.github/workflows/ci_test_net.yml

chore: test "dotnet pack" in CI

---

DynamoDbEncryption/runtimes/net/DynamoDbEncryption.csproj
TestVectors/runtimes/net/DbEsdkTestVectors.csproj
project.properties

chore: bump MPL to 1.4

---

project.properties

chore: update project.properties to be SNAPSHOT

---

Makefile

We made this change because of this [issue](https://github.com/semantic-release/release-notes-generator/issues/633) in semantic-release. Now, it is resolved in its latest version, I am reverting this change.

chore(CI/CD): use latest conventional-changelog-conventionalcommits

---

DynamoDbEncryption/runtimes/net/DynamoDbEncryption.csproj
TestVectors/runtimes/java/build.gradle.kts
TestVectors/runtimes/net/DbEsdkTestVectors.csproj
project.properties

chore(MPL): Bump MPL to 1.5.1

---

.github/workflows/nightly.yml

This automation creates a lot of noise on `dafny-lang/dafny`. Instead of always creating new issues, we create a comment, when possible.

chore: Try to update existing issues

---

cfn/CB-Staging.yml
codebuild/release/release-prod.yml

chore: Sonatype Migration to User Tokens

---

project.properties

chore: update version to snapshot

---

project.properties

chore: Enable local testing

---

.github/workflows/dafny-interop.yml
.github/workflows/dafny_interop_java.yml

chore(GHA): add backwards interop dafny tests

---

.github/workflows/dafny_interop_test_vector_java.yml
.github/workflows/dafny_interop_test_vector_net.yml

chore(GHA): fix test vector dafny interop

---

.github/workflows/nightly.yml

chore: fix nightly gha

---

project.properties

chore: allow local testing

---

.github/workflows/check_only_key_word.yml

chore: add check only keyword action

---

codebuild/release/release-prod.yml
codebuild/release/validate-release.yml
codebuild/staging/release-staging.yml
codebuild/staging/validate-staging.yml

chore: fix dafny version release scripts

---

.github/actions/polymorph_codegen/action.yml
.github/workflows/ci_codegen.yml

chore: always use dotnet 6 for format checking.

---

project.properties

chore(Java): bump conversion library

---

.github/workflows/ci_examples_java.yml
.github/workflows/ci_examples_net.yml
.github/workflows/ci_test_java.yml
.github/workflows/ci_test_net.yml
.github/workflows/ci_todos.yml
.github/workflows/dafny_interop_examples_java.yml
.github/workflows/dafny_interop_examples_net.yml
.github/workflows/dafny_interop_java.yml
.github/workflows/dafny_interop_test_net.yml
.github/workflows/library_dafny_verification.yml
.github/workflows/library_format.yml
.github/workflows/sem_ver.yml
.github/workflows/semantic_release.yml
.github/workflows/test_vector_verification.yml

chore: bump macos from 12 to 13 in CI

---

DynamoDbEncryption/runtimes/net/DynamoDbEncryption.csproj

fix: Upgrade .net DDB SDK

---

.github/dependabot.yml

chore: add dependabot for rust

---

DynamoDbEncryption/runtimes/rust/Cargo.toml
DynamoDbEncryption/runtimes/rust/test_examples/Cargo.toml
TestVectors/runtimes/rust/Cargo.toml

chore: update MPL

---

DynamoDbEncryption/runtimes/rust/examples/basic_get_put_example.rs
DynamoDbEncryption/runtimes/rust/examples/clientsupplier/client_supplier_example.rs
DynamoDbEncryption/runtimes/rust/examples/clientsupplier/regional_role_client_supplier.rs
DynamoDbEncryption/runtimes/rust/examples/create_keystore_key.rs
DynamoDbEncryption/runtimes/rust/examples/get_encrypted_data_key_description.rs
DynamoDbEncryption/runtimes/rust/examples/itemencryptor/item_encrypt_decrypt.rs
DynamoDbEncryption/runtimes/rust/examples/keyring/branch_key_id_supplier.rs
DynamoDbEncryption/runtimes/rust/examples/keyring/hierarchical_keyring.rs
DynamoDbEncryption/runtimes/rust/examples/keyring/kms_rsa_keyring.rs
DynamoDbEncryption/runtimes/rust/examples/keyring/mrk_discovery_multi_keyring.rs
DynamoDbEncryption/runtimes/rust/examples/keyring/multi_keyring.rs
DynamoDbEncryption/runtimes/rust/examples/keyring/multi_mrk_keyring.rs
DynamoDbEncryption/runtimes/rust/examples/keyring/raw_aes_keyring.rs
DynamoDbEncryption/runtimes/rust/examples/keyring/raw_rsa_keyring.rs
DynamoDbEncryption/runtimes/rust/examples/multi_get_put_example.rs
DynamoDbEncryption/runtimes/rust/examples/searchableencryption/basic_searchable_encryption.rs
DynamoDbEncryption/runtimes/rust/examples/searchableencryption/beacon_styles_searchable_encryption.rs
DynamoDbEncryption/runtimes/rust/examples/searchableencryption/complexexample/beacon_config.rs
DynamoDbEncryption/runtimes/rust/examples/searchableencryption/compound_beacon_searchable_encryption.rs
DynamoDbEncryption/runtimes/rust/examples/searchableencryption/virtual_beacon_searchable_encryption.rs
DynamoDbEncryption/runtimes/rust/src/lib.rs

chore: change exported names, update docs

---

DynamoDbEncryption/runtimes/rust/README.md

chore(README): point to release examples

---

.github/workflows/ci_test_vector_java.yml
.github/workflows/pull.yml

chore(GHA): Add pr-ci-all-required to pull.yaml; use ubuntu-22.04 instead of ubuntu-latest in CI

---

.github/workflows/check-files.yml
.github/workflows/check_only_key_word.yml
.github/workflows/ci_codegen.yml
.github/workflows/ci_duvet.yml
.github/workflows/ci_static_analysis.yml
.github/workflows/ci_test_net.yml
.github/workflows/ci_test_vector_net.yml
.github/workflows/dafny_interop_test_net.yml
.github/workflows/dafny_interop_test_vector_java.yml
.github/workflows/dafny_interop_test_vector_net.yml
.github/workflows/dafny_verify_version.yml
.github/workflows/dafny_version.yml
.github/workflows/library_rust_tests.yml
.github/workflows/mpl_head_version.yml
.github/workflows/nightly.yml
.github/workflows/smithy-diff.yml

chore(gha): use ubuntu-22.04

---

.github/workflows/dafny_interop_examples_java.yml
.github/workflows/dafny_interop_examples_net.yml
.github/workflows/dafny_interop_java.yml
.github/workflows/dafny_interop_test_net.yml
.github/workflows/dafny_interop_test_vector_java.yml
.github/workflows/dafny_interop_test_vector_net.yml
.github/workflows/mpl_head_version.yml

chore(gha): fix workflows triggered by dafny-interop.yml

---

TestVectors/runtimes/java/build.gradle.kts
project.properties

chore(mpl): Bump to 1.9.0

---

CHANGELOG.md

chore(release): Re-update CHANGELOG for v3.8.0

---

project.properties

chore(java): allow local testing v3.8.0

---

DynamoDbEncryption/runtimes/java/build.gradle.kts
Examples/runtimes/java/Migration/DDBECToAWSDBE/build.gradle.kts

chore(java): update versions of lombok and aws-sdk-ddb

---

project.properties

chore(dafny): update project.properties and mpl submodule

---

DynamoDbEncryption/runtimes/rust/Cargo.toml
DynamoDbEncryption/runtimes/rust/start_release.sh
TestVectors/runtimes/rust/Cargo.toml
releases/rust/db_esdk/dafny_runtime_rust/Cargo.toml
releases/rust/db_esdk/dafny_runtime_rust/src/big_int.rs
releases/rust/db_esdk/dafny_runtime_rust/src/lib.rs
releases/rust/db_esdk/dafny_runtime_rust/src/small_int.rs
releases/rust/db_esdk/dafny_runtime_rust/src/system/mod.rs
releases/rust/db_esdk/dafny_runtime_rust/src/tests/mod.rs

All of the changes in 
releases/rust/db_esdk/dafny_runtime_rust/Cargo.toml
are copied exactly from
https://github.com/dafny-lang/dafny/tree/master/Source/DafnyRuntime/DafnyRuntimeRust
which is also the same as
https://github.com/smithy-lang/smithy-dafny/tree/main-1.x/TestModels/dafny-dependencies/dafny_runtime_rust
When this is approved, I will publish version 0.3.0 of the Rust crate dafny_runtime.

chore(rust): update dafny runtime release

---

.github/workflows/ci_codegen.yml
.github/workflows/ci_examples_java.yml
.github/workflows/ci_examples_net.yml
.github/workflows/ci_test_java.yml
.github/workflows/ci_test_latest_released_mpl_java.yml
.github/workflows/ci_test_net.yml
.github/workflows/ci_test_vector_java.yml
.github/workflows/ci_test_vector_net.yml
.github/workflows/library_dafny_verification.yml
.github/workflows/test_vector_verification.yml

chore: install smithy-dafny dependencies in github workflows

---

DynamoDbEncryption/runtimes/go/ImplementationFromDafny-go/dbesdkmiddleware/middleware.go

https://github.com/aws/aws-database-encryption-sdk-dynamodb/pull/1861#discussion_r2116353202
https://github.com/aws/aws-database-encryption-sdk-dynamodb/pull/1861#discussion_r2116359003
- Both of the changes made here (Change name of middleware func id and sending context to smithy layer) does not have any effect right now but done looking if anything changes in future.

chore(go): nits to middleware 

---

project.properties

chore(deps): Bump MPL version to 1.11.0

---

.github/workflows/daily_ci.yml
.github/workflows/issue-notification.yml

- Adding slacking notification on daily CI failure and issue creation.

chore(CI): add slack notifications 
