aws/aws-database-encryption-sdk-dynamodb

SharedMakefile.mk
Same change as https://github.com/aws/aws-cryptographic-material-providers-library-java/pull/58
=> fix: Provide -compileSuffix to dafny when available

DynamoDbEncryption/runtimes/java/src/main/java/software/amazon/cryptography/dbencryptionsdk/dynamodb/enhancedclient/DynamoDbEnhancedClientEncryption.java
`TableSchema`'s store Index information in `indices`, NOT `keyAttributes`.
`keyAttributes` includes Index information, 
but also includes other information about non-Index related attributes.
For example, the Enhanced Client's `AutoGeneratedTimestampRecordExtension` persists 
non-index information in `keyAttributes`.
Furthermore, the Java Doc for `keyAttributes` reads:
> Returns metadata about all the known 'key' attributes for this table, such as primary and secondary index keys, **or any other attribute that forms part of the structure of the table**.
While `indices` reads:
> Returns metadata about all the known indices for this table.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
=> fix(EnhancedClient): Correctly Identify Index attributes

DynamoDbEncryption/runtimes/java/src/test/java/software/amazon/cryptography/dbencryptionsdk/dynamodb/enhancedclient/DynamoDbEncryptionEnhancedClientIntegrationTests.java
Updating a test to be less restrictive about the expected error from KMS. The purpose of the test is to ensure that we are receiving an SDK-like exception type, not that we always get back a very specific KMS exception back. This update makes the test less brittle and susceptible to changes in the environment running the test.
=> fix: Fix overperscriptive test for KmsException

DynamoDbEncryption/dafny/DynamoDbEncryption/src/FilterExpr.dfy, DynamoDbEncryption/dafny/DynamoDbEncryption/test/FilterExpr.dfy
=> feat: allow underscores in variable names

DynamoDbEncryption/dafny/DynamoDbItemEncryptor/src/AwsCryptographyDbEncryptionSdkDynamoDbItemEncryptorOperations.dfy, DynamoDbEncryption/dafny/DynamoDbItemEncryptor/test/DynamoDBItemEncryptorTest.dfy, DynamoDbEncryption/runtimes/java/src/test/java/software/amazon/cryptography/dbencryptionsdk/dynamodb/DynamoDbEncryptionInterceptorTest.java
=> feat: improve error message for missing key

.github/workflows/ci_test_java.yml, .github/workflows/ci_test_vector_java.yml, DynamoDbEncryption/dafny/DynamoDbEncryption/Model/DynamoDbEncryption.smithy, DynamoDbEncryption/dafny/DynamoDbEncryption/src/DDBSupport.dfy, DynamoDbEncryption/dafny/DynamoDbEncryption/src/Virtual.dfy, DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/Model/AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.dfy, DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/Model/DynamoDbEncryptionTransforms.smithy, DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/src/AttributeResolver.dfy, DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/src/AwsCryptographyDbEncryptionSdkDynamoDbTransformsOperations.dfy, DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/src/DynamoDbMiddlewareSupport.dfy, DynamoDbEncryption/runtimes/java/build.gradle.kts, DynamoDbEncryption/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/dbencryptionsdk/dynamodb/transforms/DynamoDbEncryptionTransforms.java, DynamoDbEncryption/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/dbencryptionsdk/dynamodb/transforms/ToDafny.java, DynamoDbEncryption/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/dbencryptionsdk/dynamodb/transforms/ToNative.java, DynamoDbEncryption/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/dbencryptionsdk/dynamodb/transforms/model/ResolveAttributesInput.java, DynamoDbEncryption/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/dbencryptionsdk/dynamodb/transforms/model/ResolveAttributesOutput.java, Examples/runtimes/java/DynamoDbEncryption/build.gradle.kts, Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/searchableencryption/CompoundBeaconSearchableEncryptionExample.java, Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/searchableencryption/VirtualBeaconSearchableEncryptionExample.java, Examples/runtimes/java/Migration/DDBECToAWSDBE/build.gradle.kts, Examples/runtimes/java/Migration/PlaintextToAWSDBE/build.gradle.kts, TestVectors/runtimes/java/build.gradle.kts
Add ResolveAttribute
Also change build to preferentially use MavenLocal over MavenCentral
=> feat: add ResolveAttribute

DynamoDbEncryption/dafny/DynamoDbEncryption/src/CompoundBeacon.dfy, DynamoDbEncryption/dafny/DynamoDbEncryption/test/Beacon.dfy
A malformed Compound Beacon (e.g B_foo.A_bar when the only constructor is A_.B_) used to silently return no results. Now it gives a proper error message.
=> feat: error on query with impossible compound beacons

DynamoDbEncryption/dafny/DynamoDbEncryption/Model/AwsCryptographyDbEncryptionSdkDynamoDbTypes.dfy, DynamoDbEncryption/dafny/DynamoDbEncryption/Model/DynamoDbEncryption.smithy, DynamoDbEncryption/dafny/DynamoDbEncryption/src/Beacon.dfy, DynamoDbEncryption/dafny/DynamoDbEncryption/src/CompoundBeacon.dfy, DynamoDbEncryption/dafny/DynamoDbEncryption/src/ConfigToInfo.dfy, DynamoDbEncryption/dafny/DynamoDbEncryption/src/DynamoToStruct.dfy, DynamoDbEncryption/dafny/DynamoDbEncryption/src/FilterExpr.dfy, DynamoDbEncryption/dafny/DynamoDbEncryption/src/SearchInfo.dfy, DynamoDbEncryption/dafny/DynamoDbEncryption/test/Beacon.dfy, DynamoDbEncryption/dafny/DynamoDbEncryption/test/BeaconTestFixtures.dfy, DynamoDbEncryption/dafny/DynamoDbEncryption/test/ConfigToInfo.dfy, DynamoDbEncryption/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/dbencryptionsdk/dynamodb/ToDafny.java, DynamoDbEncryption/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/dbencryptionsdk/dynamodb/ToNative.java, DynamoDbEncryption/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/dbencryptionsdk/dynamodb/model/AsSet.java, DynamoDbEncryption/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/dbencryptionsdk/dynamodb/model/BeaconStyle.java, DynamoDbEncryption/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/dbencryptionsdk/dynamodb/model/BeaconVersion.java, DynamoDbEncryption/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/dbencryptionsdk/dynamodb/model/PartOnly.java, DynamoDbEncryption/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/dbencryptionsdk/dynamodb/model/StandardBeacon.java, DynamoDbEncryption/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/dbencryptionsdk/dynamodb/model/Twinned.java, DynamoDbEncryption/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/dbencryptionsdk/dynamodb/model/TwinnedSet.java, DynamoDbEncryption/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/dbencryptionsdk/dynamodb/transforms/DynamoDbEncryptionTransforms.java, Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/searchableencryption/CompoundBeaconSearchableEncryptionExample.java, Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/searchableencryption/VirtualBeaconSearchableEncryptionExample.java, TestVectors/dafny/DDBEncryption/src/TestVectors.dfy, specification/searchable-encryption/beacons.md
=> feat: implement beacon styles

DynamoDbEncryption/dafny/DynamoDbItemEncryptor/src/InternalLegacyOverride.dfy, DynamoDbEncryption/runtimes/java/src/main/java/software/amazon/cryptography/dbencryptionsdk/dynamodb/itemencryptor/internal/InternalLegacyOverride.java, DynamoDbEncryption/runtimes/java/src/main/java/software/amazon/cryptography/dbencryptionsdk/dynamodb/itemencryptor/internaldafny/legacy/InternalLegacyOverride.java, DynamoDbEncryption/runtimes/java/src/test/sdkv1/com/amazonaws/services/dynamodbv2/datamodeling/LegacyTestVectors.java, DynamoDbEncryption/runtimes/net/Extern/InternalLegacyConfig.cs
=> feat: dont use internal, because it is reserved in dotnet

DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/Model/AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.dfy, DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/Model/DynamoDbEncryptionTransforms.smithy, DynamoDbEncryption/dafny/DynamoDbItemEncryptor/Model/AwsCryptographyDbEncryptionSdkDynamoDbItemEncryptorTypes.dfy, DynamoDbEncryption/dafny/DynamoDbItemEncryptor/Model/DynamoDbItemEncryptor.smithy, DynamoDbEncryption/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/dbencryptionsdk/dynamodb/itemencryptor/ToNative.java, DynamoDbEncryption/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/dbencryptionsdk/dynamodb/transforms/ToNative.java, DynamoDbEncryption/runtimes/net/DynamoDbEncryption.csproj
=> feat: repair dependencies in item encryptor

DynamoDbEncryption/dafny/DynamoDbEncryption/Model/AwsCryptographyDbEncryptionSdkDynamoDbTypes.dfy, DynamoDbEncryption/dafny/DynamoDbEncryption/Model/DynamoDbEncryption.smithy, DynamoDbEncryption/dafny/DynamoDbEncryption/src/Beacon.dfy, DynamoDbEncryption/dafny/DynamoDbEncryption/src/ConfigToInfo.dfy, DynamoDbEncryption/dafny/DynamoDbEncryption/src/FilterExpr.dfy, DynamoDbEncryption/dafny/DynamoDbEncryption/src/SearchInfo.dfy, DynamoDbEncryption/dafny/DynamoDbEncryption/test/Beacon.dfy, DynamoDbEncryption/dafny/DynamoDbEncryption/test/BeaconTestFixtures.dfy, DynamoDbEncryption/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/dbencryptionsdk/dynamodb/ToDafny.java, DynamoDbEncryption/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/dbencryptionsdk/dynamodb/ToNative.java, DynamoDbEncryption/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/dbencryptionsdk/dynamodb/model/BeaconVersion.java, DynamoDbEncryption/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/dbencryptionsdk/dynamodb/model/CompoundBeacon.java, Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/searchableencryption/BeaconStylesSearchableEncryptionExample.java, Examples/runtimes/java/DynamoDbEncryption/src/test/java/software/amazon/cryptography/examples/searchableencryption/TestBeaconStylesSearchableEncryptionExample.java, TestVectors/dafny/DDBEncryption/src/TestVectors.dfy, specification/searchable-encryption/beacons.md, specification/searchable-encryption/search-config.md
=> feat: Global Parts List

DynamoDbEncryption/dafny/DynamoDbEncryption/Model/AwsCryptographyDbEncryptionSdkDynamoDbTypes.dfy, DynamoDbEncryption/dafny/DynamoDbEncryption/Model/DynamoDbEncryption.smithy, DynamoDbEncryption/dafny/DynamoDbEncryption/src/Beacon.dfy, DynamoDbEncryption/dafny/DynamoDbEncryption/src/ConfigToInfo.dfy, DynamoDbEncryption/dafny/DynamoDbEncryption/test/Beacon.dfy, DynamoDbEncryption/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/dbencryptionsdk/dynamodb/ToDafny.java, DynamoDbEncryption/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/dbencryptionsdk/dynamodb/ToNative.java, DynamoDbEncryption/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/dbencryptionsdk/dynamodb/model/BeaconStyle.java, DynamoDbEncryption/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/dbencryptionsdk/dynamodb/model/Shared.java, DynamoDbEncryption/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/dbencryptionsdk/dynamodb/model/SharedSet.java, DynamoDbEncryption/runtimes/net/Generated/DynamoDbEncryption/BeaconStyle.cs, DynamoDbEncryption/runtimes/net/Generated/DynamoDbEncryption/OpaqueError.cs, DynamoDbEncryption/runtimes/net/Generated/DynamoDbEncryption/Shared.cs, DynamoDbEncryption/runtimes/net/Generated/DynamoDbEncryption/SharedSet.cs, DynamoDbEncryption/runtimes/net/Generated/DynamoDbEncryption/TypeConversion.cs, DynamoDbEncryption/runtimes/net/Generated/DynamoDbEncryptionTransforms/OpaqueError.cs, DynamoDbEncryption/runtimes/net/Generated/DynamoDbEncryptionTransforms/TypeConversion.cs, DynamoDbEncryption/runtimes/net/Generated/DynamoDbItemEncryptor/OpaqueError.cs, DynamoDbEncryption/runtimes/net/Generated/DynamoDbItemEncryptor/TypeConversion.cs, DynamoDbEncryption/runtimes/net/Generated/StructuredEncryption/OpaqueError.cs, Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/searchableencryption/BeaconStylesSearchableEncryptionExample.java, SharedMakefile.mk, specification/searchable-encryption/beacons.md
=> feat: change twinned beacons to shared beacons

DynamoDbEncryption/dafny/DynamoDbEncryption/src/FilterExpr.dfy
=> feat: remove recursion from FilterItems

DynamoDbEncryption/dafny/DynamoDbEncryption/src/SearchInfo.dfy
Should fix issue of not being able to build locally on Dafny 4.2. Confirmed I get the assertion failure in `ResolveTopLevelDecls_Core` without this fix.
=> fix: Avoid stacking newtype definition to avoid bug fixed by Dafny PR #4569

Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/searchableencryption/CompoundBeaconSearchableEncryptionExample.java, Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/searchableencryption/VirtualBeaconSearchableEncryptionExample.java, codebuild/release/release-prod.yml, codebuild/release/release.yml
=> chore: Examples run serially. Examples wait for GSI. No extra checkout

CHANGELOG.md, DecryptWithPermute/runtimes/java/build.gradle.kts, DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/src/DeleteItemTransform.dfy, DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/src/DynamoDbMiddlewareSupport.dfy, DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/src/PutItemTransform.dfy, DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/src/UpdateItemTransform.dfy, DynamoDbEncryption/runtimes/java/build.gradle.kts, DynamoDbEncryption/runtimes/java/src/main/java/software/amazon/cryptography/dbencryptionsdk/dynamodb/DynamoDbEncryptionInterceptor.java, DynamoDbEncryption/runtimes/java/src/main/sdkv1/com/amazonaws/services/dynamodbv2/datamodeling/encryption/DoNotEncrypt.java, DynamoDbEncryption/runtimes/java/src/main/sdkv1/com/amazonaws/services/dynamodbv2/datamodeling/encryption/DoNotTouch.java, DynamoDbEncryption/runtimes/java/src/test/java/software/amazon/cryptography/dbencryptionsdk/dynamodb/DynamoDbEncryptionInterceptorIntegrationTests.java, DynamoDbEncryption/runtimes/java/src/test/java/software/amazon/cryptography/dbencryptionsdk/dynamodb/enhancedclient/DynamoDbEncryptionEnhancedClientIntegrationTests.java, DynamoDbEncryption/runtimes/java/src/test/java/software/amazon/cryptography/dbencryptionsdk/dynamodb/enhancedclient/validdatamodels/AllTypesClass.java, Examples/runtimes/java/DynamoDbEncryption/build.gradle.kts, Examples/runtimes/java/Migration/DDBECToAWSDBE/build.gradle.kts, Examples/runtimes/java/Migration/PlaintextToAWSDBE/build.gradle.kts, TestVectors/runtimes/java/build.gradle.kts, specification/dynamodb-encryption-client/ddb-sdk-integration.md
Fixes an issue where, when using the DynamoDbEncryptionInterceptor,
an encrypted item in the Attributes field of a DeleteItem, PutItem, or UpdateItem
response was passed through unmodified instead of being decrypted.
=> Fix: Decrypt attributes returned by all DDB APIs

.github/workflows/ci_test_net.yml, .github/workflows/ci_test_vector_net.yml, DynamoDbEncryption/codebuild/release-prod.yml, DynamoDbEncryption/codebuild/release-staging.yml, DynamoDbEncryption/codebuild/release.yml, DynamoDbEncryption/codebuild/sign.yml, DynamoDbEncryption/codebuild/test-prod.yml, DynamoDbEncryption/codebuild/verify.yml, DynamoDbEncryption/runtimes/java/build.gradle.kts, DynamoDbEncryption/runtimes/net/AssemblyInfo.cs, DynamoDbEncryption/runtimes/net/DynamoDbEncryption.csproj, DynamoDbEncryption/runtimes/net/tests/Test-DynamoDbEncryption.csproj, SharedMakefile.mk, codebuild/net/signing_lib.py, codebuild/release/release-prod.yml, codebuild/release/validate-release.yml, codebuild/staging/release-staging.yml, codebuild/staging/validate-staging.yml
=> chore: add .NET release steps

DynamoDbEncryption/runtimes/java/src/main/java/software/amazon/cryptography/dbencryptionsdk/dynamodb/enhancedclient/DynamoDbEnhancedClientEncryption.java, DynamoDbEncryption/runtimes/java/src/main/java/software/amazon/cryptography/dbencryptionsdk/dynamodb/enhancedclient/DynamoDbEnhancedTableEncryptionConfig.java, DynamoDbEncryption/runtimes/java/src/test/java/software/amazon/cryptography/dbencryptionsdk/dynamodb/enhancedclient/DynamoDbEnhancedClientEncryptionTest.java, DynamoDbEncryption/runtimes/java/src/test/java/software/amazon/cryptography/dbencryptionsdk/dynamodb/enhancedclient/validdatamodels/SingleTable1.java, DynamoDbEncryption/runtimes/java/src/test/java/software/amazon/cryptography/dbencryptionsdk/dynamodb/enhancedclient/validdatamodels/SingleTable2.java, DynamoDbEncryption/runtimes/java/src/test/java/software/amazon/cryptography/dbencryptionsdk/dynamodb/enhancedclient/validdatamodels/SingleTable3.java, Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/enhanced/SimpleClass2.java, Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/enhanced/SimpleClass3.java, Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/enhanced/SingleTableExample.java, Examples/runtimes/java/DynamoDbEncryption/src/test/java/software/amazon/cryptography/examples/enhanced/TestSingleTableExample.java
=> feat: better support of single table design

DynamoDbEncryption/dafny/DynamoDbEncryption/src/DynamoToStruct.dfy, DynamoDbEncryption/dafny/DynamoDbEncryption/src/Util.dfy
Remove the arbitrary limitations on list length and map size.
Keep the limit (32) on structure depth.
In earlier versions, it was thought that there might be a performance bottleneck in dealing with large maps and lists, but some code refinements and further testing showed that this was not the case, and that there was no need to limit customers in this way. Also, the 400K limit on an item puts an upper bound on structure complexity.
=> feat: remove limits on list length and map size

Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/searchableencryption/CompoundBeaconSearchableEncryptionExample.java, Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/searchableencryption/complexexample/BeaconConfig.java
=> feat: update examples for newest best practices

DynamoDbEncryption/codebuild/release-staging.yml, DynamoDbEncryption/codebuild/test-prod.yml
=> chore: repair json file names

.github/workflows/ci_tv_verification.yml, TestVectors/dafny/DDBEncryption/src/TestVectors.dfy
=> chore: add verify test for test vectors

.github/workflows/sem_ver.yml, .github/workflows/semantic_release.yml, .releaserc.cjs, Makefile
=> chore(CI/CD): add semantic release automation

.github/workflows/ci_todos.yml, DynamoDbEncryption/dafny/DynamoDbItemEncryptor/src/AwsCryptographyDbEncryptionSdkDynamoDbItemEncryptorOperations.dfy, TestVectors/README.md, TestVectors/dafny/DDBEncryption/src/DecryptManifest.dfy, TestVectors/dafny/DDBEncryption/src/EncryptManifest.dfy, TestVectors/dafny/DDBEncryption/src/TestVectors.dfy, TestVectors/dafny/DDBEncryption/src/WriteManifest.dfy, specification/dynamodb-encryption-client/decrypt-item.md
Add test vectors to cover all permutations of encrypt and decrypt configurations.
Fix bug found decrypting V2 items with V1 Config and vice versa.
=> feat: more test vectors

.github/workflows/ci_examples_java.yml, .github/workflows/ci_examples_net.yml, .github/workflows/ci_test_java.yml, .github/workflows/ci_test_net.yml, .github/workflows/ci_todos.yml, .github/workflows/ci_tv_verification.yml, .github/workflows/ci_verification.yml, .github/workflows/sem_ver.yml, .github/workflows/semantic_release.yml, DynamoDbEncryption/dafny/DynamoDbItemEncryptor/test/DynamoDBItemEncryptorTest.dfy, TestVectors/dafny/DDBEncryption/src/WriteManifest.dfy
=> chore(test): add tests for attribute names that seem structured

DynamoDbEncryption/dafny/DynamoDbEncryption/Model/DynamoDbEncryption.smithy, DynamoDbEncryption/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/dbencryptionsdk/dynamodb/DynamoDbKeyBranchKeyIdSupplier.java, DynamoDbEncryption/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/dbencryptionsdk/dynamodb/IDynamoDbKeyBranchKeyIdSupplier.java, DynamoDbEncryption/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/dbencryptionsdk/dynamodb/model/GetBranchKeyIdFromDdbKeyInput.java, specification/dynamodb-encryption-client/ddb-encryption-branch-key-id-supplier.md
=> chore(docs): mention sign_and_include in javadoc for keyid supplier

.github/workflows/ci_test_vector_net.yml, DynamoDbEncryption/dafny/DynamoDbItemEncryptor/src/Index.dfy, TestVectors/dafny/DDBEncryption/src/JsonConfig.dfy, TestVectors/dafny/DDBEncryption/src/TestVectors.dfy, project.properties
=> chore: Update MPL to 1.3.0

CHANGELOG.md, DynamoDbEncryption/runtimes/net/AssemblyInfo.cs, DynamoDbEncryption/runtimes/net/DynamoDbEncryption.csproj, Makefile, project.properties
* **DynamoDbEncryption:** Add GetEncryptedDataKeyDescription operation ([https://github.com/aws/aws-database-encryption-sdk-dynamodb/pull/856](https://github.com/aws/aws-database-encryption-sdk-dynamodb/pull/856)) ([https://github.com/aws/aws-database-encryption-sdk-dynamodb/commit/8f8471a479d9e7526dd8aaa6f34c906d2a0e2dbb](https://github.com/aws/aws-database-encryption-sdk-dynamodb/commit/8f8471a479d9e7526dd8aaa6f34c906d2a0e2dbb))
* Bump MPL to 1.4 ([#1067](https://github.com/aws/aws-database-encryption-sdk-dynamodb/issues/1067)) ([51bbab5](https://github.com/aws/aws-database-encryption-sdk-dynamodb/commit/51bbab5589a5db611a3b7564a1c9703fb0de1a23)). This provides three new KMSConfiguration options when constructing a KeyStore (see …
=> chore(release): 3.5.0 

.github/workflows/ci_verification.yml, DynamoDbEncryption/dafny/StructuredEncryption/src/Canonize.dfy
=> chore: bump dafny verification version to 4.7

DynamoDbEncryption/dafny/DynamoDbEncryption/src/FilterExpr.dfy, DynamoDbEncryption/dafny/DynamoDbEncryption/test/BeaconTestFixtures.dfy, DynamoDbEncryption/dafny/DynamoDbEncryption/test/DDBSupport.dfy
=> feat: allow indirect attribute names with MultiKeyStore

CHANGELOG.md, DynamoDbEncryption/runtimes/net/AssemblyInfo.cs, DynamoDbEncryption/runtimes/net/DynamoDbEncryption.csproj, project.properties
* allow indirect attribute names with MultiKeyStore ([#1208](https://github.com/aws/aws-database-encryption-sdk-dynamodb/issues/1208)) ([4ab97bc](https://github.com/aws/aws-database-encryption-sdk-dynamodb/commit/4ab97bcc43d0b906e45c487920bc7ef5ba66e505))
* bump dafny verification version to 4.7 ([#1181](https://github.com/aws/aws-database-encryption-sdk-dynamodb/issues/1181)) ([e7801ec](https://github.com/aws/aws-database-encryption-sdk-dynamodb/commit/e7801ec42b1bb212af68f9dc0c8037eed9876b5c))
* **CI/CD:** use latest conventional-changelog-conventionalcommits ([#1195](https://github.com/aws/aws-database-encryption-sdk-dynamodb/issues/1195)) ([510227e](https://github.com/aws/aws-database-encryption-sdk-dynamodb/commit/510227eabb958ff4a17d55fc2eac83f964d6a945))
* Fix nightly build (aside …
=> chore(release): 3.6.0

TestVectors/runtimes/net/DbEsdkTestVectors.csproj
MPL Head updated the TestVectors to be an executable. This means that a Main entrypoint now gets generated in order to run the test vectors as a cli which we are now doing in CI.
However; as a project that depends on the MPL TestVectors, you cannot have two main's
defined in one .csproj. Adding `<StartupObject>DbEsdkTestVectors.Program</StartupObject>` to the
TestVectors' csproj file tells dotnet to use the TestVectors Main as opposed to the one generated by the MPL.
=> fix(TestVectors): define StartUpObject in csproj

DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/src/BatchWriteItemTransform.dfy, DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/src/DdbMiddlewareConfig.dfy, DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/src/Index.dfy, DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/src/PutItemTransform.dfy, DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/src/TransactWriteItemsTransform.dfy, DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/test/PutItemTransform.dfy, DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/test/TestFixtures.dfy
=> chore: do not add beacons when FORCE_PLAINTEXT_WRITE is used.

DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/src/QueryTransform.dfy, DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/src/ScanTransform.dfy
=> fix: allow multi-tenant queries with allow_plaintext

DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/src/DdbMiddlewareConfig.dfy, DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/src/QueryTransform.dfy, DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/src/ScanTransform.dfy, DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/test/PutItemTransform.dfy, DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/test/QueryTransform.dfy, DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/test/TestFixtures.dfy
=> chore: include bad item keys in query errors

DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/src/DdbMiddlewareConfig.dfy, DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/test/QueryTransform.dfy, Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/ScanErrorExample.java, Examples/runtimes/java/DynamoDbEncryption/src/test/java/software/amazon/cryptography/examples/TestScanErrorExample.java, Examples/runtimes/net/src/Examples.cs, Examples/runtimes/net/src/ScanErrorExample.cs
=> chore: Add examples to examine contents of query error list

CHANGELOG.md, DynamoDbEncryption/runtimes/net/AssemblyInfo.cs, DynamoDbEncryption/runtimes/net/DynamoDbEncryption.csproj, project.properties
* allow multi-tenant queries with allow_plaintext ([#1240](https://github.com/aws/aws-database-encryption-sdk-dynamodb/issues/1240)) ([1487d7e](https://github.com/aws/aws-database-encryption-sdk-dynamodb/commit/1487d7efe740920b5d8c7b30579947b6b3d26d12))
* **TestVectors:** define StartUpObject in csproj ([#1231](https://github.com/aws/aws-database-encryption-sdk-dynamodb/issues/1231)) ([2f97bf3](https://github.com/aws/aws-database-encryption-sdk-dynamodb/commit/2f97bf365e2d027103cd9eb2b1951752a3687e3c))
* Add examples to examine contents of query error list ([#1251](https://github.com/aws/aws-database-encryption-sdk-dynamodb/issues/1251)) ([b5705ee](https://github.com/aws/aws-database-encryption-sdk-dynamodb/commit/b5705ee12257fb18f867478bf17ba31f50c26c8b))
* **CI:** add smithy diff …
=> chore(release): 3.6.1

DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/test/QueryTransform.dfy, DynamoDbEncryption/dafny/StructuredEncryption/src/Footer.dfy
=> fix: update error message

.github/workflows/dafny-interop.yml, .github/workflows/dafny_interop_examples_java.yml, .github/workflows/dafny_interop_examples_net.yml, .github/workflows/dafny_interop_test_net.yml, .github/workflows/dafny_interop_test_vector_java.yml, .github/workflows/dafny_interop_test_vector_net.yml, .github/workflows/nightly.yml
=> chore(GHA): update nightlies for interop and interop action

.github/workflows/dafny_interop_test_vector_java.yml, .github/workflows/dafny_interop_test_vector_net.yml
=> chore(GHA): another gha fix

.github/workflows/dafny-interop.yml, .github/workflows/dafny_interop_examples_java.yml, .github/workflows/dafny_interop_java.yml, .github/workflows/dafny_interop_test_vector_java.yml, .github/workflows/dafny_interop_test_vector_net.yml, .github/workflows/mpl-head.yml, .github/workflows/mpl_head_version.yml, project.properties
=> chore: fix dafny interop build steps

.github/workflows/library_dafny_verification.yml
At some point `.github/actions/polymorph_codegen` composite action broke because of changes in reusable workflows. This doesn't fix all errors in the nightly build but lets it get much further: https://github.com/aws/aws-database-encryption-sdk-dynamodb/actions/runs/10478916837/job/29023359021
=> fix: ...the nightly build. Again.

TestVectors/dafny/DDBEncryption/src/DecryptManifest.dfy, TestVectors/dafny/DDBEncryption/src/EncryptManifest.dfy
=> chore: add timing output to test vectors

DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/src/QueryTransform.dfy, DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/src/ScanTransform.dfy, DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/test/QueryTransform.dfy
=> fix: revert change in error type

.github/workflows/mpl-head.yml
=> chore: fix ci mpl head gha

CHANGELOG.md, DynamoDbEncryption/runtimes/net/AssemblyInfo.cs, DynamoDbEncryption/runtimes/net/DynamoDbEncryption.csproj, project.properties
* ...the nightly build. Again. ([#1297](https://github.com/aws/aws-database-encryption-sdk-dynamodb/issues/1297)) ([b7a91c9](https://github.com/aws/aws-database-encryption-sdk-dynamodb/commit/b7a91c91fe5b52cbd9dbec9c3953770ed02fd0bf))
* revert change in error type ([#1304](https://github.com/aws/aws-database-encryption-sdk-dynamodb/issues/1304)) ([33d7ee4](https://github.com/aws/aws-database-encryption-sdk-dynamodb/commit/33d7ee4ad73f621a5fb247693981af0d35f40d54))
* add timing output to test vectors ([#1298](https://github.com/aws/aws-database-encryption-sdk-dynamodb/issues/1298)) ([30dfaa8](https://github.com/aws/aws-database-encryption-sdk-dynamodb/commit/30dfaa8dad218c48b115f6244b8125dbc4dad1ea))
* Enable local testing ([#1278](https://github.com/aws/aws-database-encryption-sdk-dynamodb …
=> chore(release): 3.6.2

DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/src/BatchGetItemTransform.dfy, DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/src/BatchWriteItemTransform.dfy, DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/src/Index.dfy
=> fix: remove usage of `:|`

DynamoDbEncryption/dafny/DynamoDbEncryption/Model/DynamoDbEncryption.smithy, DynamoDbEncryption/dafny/DynamoDbItemEncryptor/Model/DynamoDbItemEncryptor.smithy, DynamoDbEncryption/dafny/StructuredEncryption/Model/StructuredEncryption.smithy
=> chore: remove /// from smithy files

DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/src/QueryTransform.dfy, DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/src/ScanTransform.dfy
=> chore: remove assert to fix verification

CHANGELOG.md, DynamoDbEncryption/runtimes/net/AssemblyInfo.cs, DynamoDbEncryption/runtimes/net/DynamoDbEncryption.csproj, project.properties
* bump to dafny 4.8.0 and mpl 1.6.0 ([#1356](https://github.com/aws/aws-database-encryption-sdk-dynamodb/issues/1356)) ([fedc0ad](https://github.com/aws/aws-database-encryption-sdk-dynamodb/commit/fedc0ad2d490eaa853c103cae2cb7406c526a550))
* remove usage of `:|` ([#1320](https://github.com/aws/aws-database-encryption-sdk-dynamodb/issues/1320)) ([eeb3f51](https://github.com/aws/aws-database-encryption-sdk-dynamodb/commit/eeb3f513ab7a27c62a97529a0a94c1933da1422c))
* add check only keyword action ([#1327](https://github.com/aws/aws-database-encryption-sdk-dynamodb/issues/1327)) ([5d777d6](https://github.com/aws/aws-database-encryption-sdk-dynamodb/commit/5d777d6aa975831ef0ce3faeb0b848a1eb108981))
* add ddb local to dafny interop test vectors …
=> chore(release): 3.7.0

.github/workflows/smithy-diff.yml
=> chore(CI): make smithy diff check smarter

DynamoDbEncryption/dafny/DynamoDbEncryption/src/SearchInfo.dfy
The CMC model indicates that a cache miss is an EntryDoesNotExist error.
But other exceptions should not be swallowed.
The CMC model indicates that a cache put MAY throw a EntryAlreadyExists error.
Such an exception should be ignored.
=> fix(SearchableEncryption): respect CMC contract

.github/workflows/check-files.yml, .github/workflows/semantic_release.yml
=> chore: update Github alias

DynamoDbEncryption/runtimes/rust/Cargo.toml, releases/rust/db_esdk/Cargo.toml, releases/rust/db_esdk/src/aes_kdf_ctr.rs, releases/rust/db_esdk/src/lib.rs, releases/rust/db_esdk/src/standard_library_conversions.rs, releases/rust/db_esdk/src/standard_library_externs.rs
=> chore: update for complete copyright notices

DynamoDbEncryption/runtimes/rust/RELEASE.md, DynamoDbEncryption/runtimes/rust/start_release.sh, DynamoDbEncryption/runtimes/rust/test_examples/Cargo.toml, DynamoDbEncryption/runtimes/rust/test_published.sh
=> chore(rust): add comments to release scripts

DynamoDbEncryption/dafny/DynamoDbEncryption/src/ConfigToInfo.dfy
=> fix(SearchableEncryption): disable shared cached

DynamoDbEncryption/runtimes/rust/.gitignore, DynamoDbEncryption/runtimes/rust/Cargo.toml, DynamoDbEncryption/runtimes/rust/examples/basic_get_put_example.rs, DynamoDbEncryption/runtimes/rust/examples/clientsupplier/client_supplier_example.rs, DynamoDbEncryption/runtimes/rust/examples/keyring/hierarchical_keyring.rs, DynamoDbEncryption/runtimes/rust/examples/keyring/kms_rsa_keyring.rs, DynamoDbEncryption/runtimes/rust/examples/keyring/mrk_discovery_multi_keyring.rs, DynamoDbEncryption/runtimes/rust/examples/keyring/multi_keyring.rs, DynamoDbEncryption/runtimes/rust/examples/keyring/multi_mrk_keyring.rs, DynamoDbEncryption/runtimes/rust/examples/keyring/raw_aes_keyring.rs, DynamoDbEncryption/runtimes/rust/examples/keyring/raw_rsa_keyring.rs, DynamoDbEncryption/runtimes/rust/examples/main.rs, DynamoDbEncryption/runtimes/rust/examples/multi_get_put_example.rs, DynamoDbEncryption/runtimes/rust/examples/searchableencryption/basic_searchable_encryption.rs, DynamoDbEncryption/runtimes/rust/examples/searchableencryption/beacon_styles_searchable_encryption.rs, DynamoDbEncryption/runtimes/rust/examples/searchableencryption/complexexample/beacon_config.rs, DynamoDbEncryption/runtimes/rust/examples/searchableencryption/compound_beacon_searchable_encryption.rs, DynamoDbEncryption/runtimes/rust/examples/searchableencryption/virtual_beacon_searchable_encryption.rs, DynamoDbEncryption/runtimes/rust/src/intercept.rs, DynamoDbEncryption/runtimes/rust/src/lib.rs, TestVectors/runtimes/rust/.gitignore, TestVectors/runtimes/rust/Cargo.toml, TestVectors/runtimes/rust/src/lib.rs
=> fix: support new input validation

DynamoDbEncryption/runtimes/rust/README.md, DynamoDbEncryption/runtimes/rust/src/README.md, DynamoDbEncryption/runtimes/rust/start_release.sh
=> chore(Rust-docs): Update README

DynamoDbEncryption/Makefile, DynamoDbEncryption/runtimes/rust/.gitignore, DynamoDbEncryption/runtimes/rust/copy_externs.sh, DynamoDbEncryption/runtimes/rust/src/lib.rs, TestVectors/Makefile, TestVectors/runtimes/rust/.gitignore, TestVectors/runtimes/rust/copy_externs.sh, TestVectors/runtimes/rust/src/lib.rs
=> chore: new mpl

.github/workflows/library_rust_tests.yml
=> chore(CI): mpl head step for rust

DynamoDbEncryption/dafny/DynamoDbEncryption/src/SearchInfo.dfy
=> fix(verification): Verify cache identifier

CHANGELOG.md, DynamoDbEncryption/dafny/DynamoDbEncryption/src/ConfigToInfo.dfy, codebuild/release/release-prod.yml, codebuild/release/validate-release.yml, codebuild/staging/release-staging.yml, codebuild/staging/validate-staging.yml
=> chore: fix Dafny verification

.github/workflows/ci_test_vector_net.yml, .github/workflows/dafny_interop_test_vector_net.yml, TestVectors/dafny/DDBEncryption/src/DecryptManifest.dfy, TestVectors/dafny/DDBEncryption/src/TestVectors.dfy
=> chore: add Rust generated test vectors

DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/src/BatchWriteItemTransform.dfy, DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/test/BatchWriteItemTransform.dfy, DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/test/TestFixtures.dfy, specification/dynamodb-encryption-client/ddb-sdk-integration.md
=> fix: return plaintext items in UnprocessedItems in BatchWriteIttem

.github/workflows/library_rust_tests.yml, TestVectors/Makefile, TestVectors/dafny/DDBEncryption/Model/AwsCryptographyDynamoDbEncryptionTypesWrapped.dfy, TestVectors/runtimes/rust/SkipLocal.txt, TestVectors/runtimes/rust/src/create_client.rs, TestVectors/runtimes/rust/src/intercept.rs, TestVectors/runtimes/rust/src/lib.rs
=> chore(rust): enable wrapped client test vectors

TestVectors/dafny/DDBEncryption/src/DecryptManifest.dfy, TestVectors/dafny/DDBEncryption/src/EncryptManifest.dfy, TestVectors/dafny/DDBEncryption/src/Index.dfy, TestVectors/dafny/DDBEncryption/src/TestVectors.dfy, TestVectors/dafny/DDBEncryption/src/WriteManifest.dfy, TestVectors/dafny/DDBEncryption/src/WriteSetPermutations.dfy
=> chore(dafny): let FileIO deal in uint8 rather than bv8

DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/src/DdbMiddlewareConfig.dfy, DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/src/Index.dfy, SharedMakefile.mk
Remove all Dafny warnings and set warnings to error. By removing all the errors,
--allow-warnings can be removed from verification. This means that any verification warning will now fail the build. This is especially relevant if {:only} is ever committed. See https://github.com/aws/aws-cryptographic-material-providers-library/pull/517. This would now cause CI verification to fail.
=> chore: Remove Dafny warnings

DynamoDbEncryption/dafny/DynamoDbEncryption/test/DynamoDbEncryptionBranchKeyIdSupplierTest.dfy, DynamoDbEncryption/runtimes/java/src/test/java/software/amazon/cryptography/dbencryptionsdk/dynamodb/TestUtils.java
Same as https://github.com/aws/aws-cryptographic-material-providers-library/pull/1404
=> chore: restore static test branch key id

.github/workflows/ci_test_vector_net.yml, .github/workflows/dafny_interop_test_vector_net.yml
Current CI only copies `../java/decrypt_java_*.json ../java/decrypt_dotnet_*.json ../java/decrypt_rust_*.json ../java/large_records.json .` We do also need to copy files like `data.json`
=> chore(dotnet): copy all the JSON for testvectors CI 

TestVectors/dafny/DDBEncryption/src/TestVectors.dfy
- Ran make `transpile_go`, `polymorph_go` and `test_go`. 
- Got decrypt.json in runtimes/go/testFromDafny-go which I copied to runtimes/java and renamed to `decrypt_go_38.json`
- Added `decrypt_go_38.json` to DdbEncryptionTestVectors.RunAllTests like other runtimes.
=> chore(go): Add decrypt manifest for Go 

.github/workflows/ci_examples_python.yml, .github/workflows/ci_static_analysis_python.yml, .github/workflows/ci_test_python.yml, .github/workflows/ci_test_vector_python.yml, .github/workflows/daily_ci.yml, .github/workflows/manual.yml, .github/workflows/mpl-head.yml, .github/workflows/nightly.yml, .github/workflows/pull.yml, .github/workflows/push.yml, DynamoDbEncryption/runtimes/python/tox.ini, Examples/runtimes/python/tox.ini, TestVectors/runtimes/python/tox.ini
These fail since the source code isn't all on `python-reviewed` yet.
The CI runs against the source code in https://github.com/aws/aws-database-encryption-sdk-dynamodb/pull/1794.
=> test(Python): GHA and test config files

DynamoDbEncryption/runtimes/go/ImplementationFromDafny-go/InternalLegacyOverride/extern.go
EncryptItem and DecryptItem will never be reached in Go but if it does in future we will just return error.
=> fix(go): make Encrypt and Decrypt fail always for Legacy version

DynamoDbEncryption/dafny/DynamoDbEncryption/src/FilterExpr.dfy
=> chore(dafny): bump mpl version

Examples/runtimes/go/main.go, Examples/runtimes/go/searchableencryption/basicsearchableencryptionexample.go, Examples/runtimes/go/searchableencryption/beaconstylessearchableencryptionexample.go, Examples/runtimes/go/searchableencryption/compoundbeaconsearchableencryptionexample.go, Examples/runtimes/go/searchableencryption/virtualbeaconsearchableencryptionexample.go, Examples/runtimes/go/utils/exampleUtils.go
Adds following examples:
- BasicSearchableEncryptionExample
- BeaconStylesSearchableEncryptionExample
- CompoundBeaconSearchableEncryptionExample
- VirtualBeaconSearchableEncryptionExample
=> chore(go): add Searchable Encryption Examples

Examples/runtimes/go/clientsupplier/clientsupplierexample.go, Examples/runtimes/go/clientsupplier/regionalRoleClientSupplierConfig.go, Examples/runtimes/go/clientsupplier/regionalroleclientsupplier.go, Examples/runtimes/go/main.go, Examples/runtimes/go/misc/basicputgetexample.go, Examples/runtimes/go/utils/exampleUtils.go
=> chore(go): Add client supplier and basic put get example 

cfn/CI.yaml
- This allows the DB-ESDK for Python to test the legacy extern behavior.
- See: https://docs.aws.amazon.com/database-encryption-sdk/latest/devguide/python-using.html#python-helpers
- To use the client helper classes in DDBEC, the caller must have permission to call the DynamoDB DescribeTable operation on the target table.
=> chore(cfn): add DescribeTable permission for legacy DDBEC support

.github/workflows/library_rust_tests.yml, DynamoDbEncryption/runtimes/rust/Cargo.toml, DynamoDbEncryption/runtimes/rust/src/lib.rs, TestVectors/runtimes/rust/Cargo.toml, TestVectors/runtimes/rust/src/lib.rs
=> chore(rust): fips feature
